title: jvfe's SPARQL queries
description: Some of my useful Wikidata SPARQL queries
queries_directory: ./queries/
query_template: ./templates/query.ejs
index_template: ./templates/index.ejs
output_directory: ./_site
