#+ summary: String search on a particular subset of items
#+ endpoint: https://query.wikidata.org/sparql

# (Proteins in this case). The search is done both by label and alias.

SELECT ?item ?itemLabel WHERE {

  SERVICE wikibase:mwapi {
      bd:serviceParam wikibase:endpoint "www.wikidata.org";
        wikibase:api "EntitySearch";
        mwapi:search "cyclin";
        mwapi:language "en".
      ?item wikibase:apiOutputItem mwapi:item.
  }

  SERVICE wikibase:label { 
    bd:serviceParam wikibase:language "en". 
  }
  
  ?item p:P31 ?instance_of .
  ?instance_of ps:P31 wd:Q8054 .
}
