name: website-build

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2

      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Build website
        run: |
          npm install
          node index.js

      - name: Configure git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Deploy
        run: |
          git pull
          latest=$(git rev-parse HEAD | cut -c 1-8)
          git add docs/
          git commit -m "Update site for $latest"
